-- Generated by github.com/davyxu/tabtoy
-- Version: 3.1.3

return {
	init = function( g )
		
		g.MyData = { 
			{ itemid = 1001, itemCount = 1000, itemName = "1000金币", subItemIds = {1001}, subItemIdsCount = {1000}, rate = 100, storeType = 1, }, 
			{ itemid = 1001, itemCount = 5000, itemName = "5000金币", subItemIds = {1001}, subItemIdsCount = {5000}, rate = 100, storeType = 1, }, 
			{ itemid = 1001, itemCount = 10000, itemName = "10000金币", subItemIds = {1001}, subItemIdsCount = {10000}, rate = 100, storeType = 1, }, 
			{ itemid = 1002, itemCount = 1000, itemName = "1000钻石", subItemIds = {1002}, subItemIdsCount = {1000}, rate = 100, storeType = 2, }, 
			{ itemid = 1002, itemCount = 1000, itemName = "10000钻石", subItemIds = {1002}, subItemIdsCount = {10000}, rate = 100, storeType = 2, }, 
			{ itemid = 3001, itemCount = 1, itemName = "锁定", subItemIds = {1002}, subItemIdsCount = {100}, rate = 100, storeType = 3, }, 
			{ itemid = 3002, itemCount = 1, itemName = "冰冻", subItemIds = {1002}, subItemIdsCount = {100}, rate = 100, storeType = 3, }, 
			{ itemid = 3003, itemCount = 1, itemName = "狂暴", subItemIds = {1002}, subItemIdsCount = {100}, rate = 100, storeType = 3, }, 
			{ itemid = 9001, itemCount = 1, itemName = "初级盲盒", subItemIds = {1002}, subItemIdsCount = {100}, rate = 100, storeType = 0, }, 
			{ itemid = 9002, itemCount = 1, itemName = "中级盲盒", subItemIds = {1002}, subItemIdsCount = {100}, rate = 100, storeType = 0, }, 
			{ itemid = 9003, itemCount = 1, itemName = "高级盲盒", subItemIds = {1002}, subItemIdsCount = {100}, rate = 100, storeType = 0, }, 
			{ itemid = 9004, itemCount = 1, itemName = "神秘盲盒", subItemIds = {1002}, subItemIdsCount = {100}, rate = 100, storeType = 0, },  
		}
		
		
		
		return g
	end
}
