-- Generated by github.com/davyxu/tabtoy
-- Version: 3.1.3

return {
	init = function( g )
		
		g.MyData = { 
			{ itemid = 9001, itemName = "初级盲盒", subItemIds = {6001,6002}, subItemIdsCount = {1,2}, rate = {90,80}, }, 
			{ itemid = 9002, itemName = "中级盲盒", subItemIds = {6001,6002}, subItemIdsCount = {3,4}, rate = {90,80}, }, 
			{ itemid = 9003, itemName = "高级盲盒", subItemIds = {6001,6002}, subItemIdsCount = {1,2}, rate = {90,80}, }, 
			{ itemid = 9004, itemName = "神秘盲盒", subItemIds = {6001,6002}, subItemIdsCount = {3,4}, rate = {90,80}, }, 
			{ itemid = 4001, itemName = "普通宝箱", subItemIds = {6001,6002}, subItemIdsCount = {3,4}, rate = {90,80}, }, 
			{ itemid = 5001, itemName = "5元礼包", subItemIds = {1002}, subItemIdsCount = {500}, rate = {100}, }, 
			{ itemid = 5002, itemName = "20元礼包", subItemIds = {1002}, subItemIdsCount = {1000}, rate = {100}, }, 
			{ itemid = 5003, itemName = "50元礼包", subItemIds = {1002}, subItemIdsCount = {2000}, rate = {100}, },  
		}
		
		
		
		return g
	end
}
