-- Generated by github.com/davyxu/tabtoy
-- Version: 3.1.3

return {
	init = function( g )
		
		g.MyData = { 
			{ fishType = 37, name = "钻头鱼", waitTime = 5, collideWall = 20, boomCollideWall = {2,3}, boomRadius = 500, minMultiple = 5, maxMultiple = {90,95}, launchTime = 60, flySpeed = 1300, killFishsType = {0,1,2,3,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,22,23,24,25}, killFishsPro = {100,100,100,100,100,60,60,60,60,40,40,40,30,30,30,20,20,20,15,15,15,15,15,15}, },  
		}
		
		
		
		return g
	end
}
