-- Generated by github.com/davyxu/tabtoy
-- Version: 3.1.3

return {
	init = function( g )
		
		g.MyData = { 
			{ roomName = "龜相迎賓", fishType = 0, fishName = "蜻蜓魚", createInterval = 1, createCount = 2, maxCount = 10, }, 
			{ roomName = "龜相迎賓", fishType = 1, fishName = "小醜魚", createInterval = 1, createCount = 2, maxCount = 10, }, 
			{ roomName = "龜相迎賓", fishType = 2, fishName = "小黃魚", createInterval = 1, createCount = 2, maxCount = 10, }, 
			{ roomName = "龜相迎賓", fishType = 3, fishName = "小金魚", createInterval = 1, createCount = 2, maxCount = 10, }, 
			{ roomName = "龜相迎賓", fishType = 4, fishName = "河豚", createInterval = 1, createCount = 2, maxCount = 10, }, 
			{ roomName = "龜相迎賓", fishType = 5, fishName = "烏賊", createInterval = 2, createCount = 1, maxCount = 2, }, 
			{ roomName = "龜相迎賓", fishType = 7, fishName = "小食人魚", createInterval = 2, createCount = 1, maxCount = 2, }, 
			{ roomName = "龜相迎賓", fishType = 8, fishName = "水母", createInterval = 2, createCount = 1, maxCount = 2, }, 
			{ roomName = "龜相迎賓", fishType = 9, fishName = "海龜", createInterval = 2, createCount = 1, maxCount = 2, }, 
			{ roomName = "龜相迎賓", fishType = 10, fishName = "孔雀魚", createInterval = 3, createCount = 1, maxCount = 1, }, 
			{ roomName = "龜相迎賓", fishType = 11, fishName = "大嘴魚", createInterval = 3, createCount = 1, maxCount = 1, }, 
			{ roomName = "龜相迎賓", fishType = 12, fishName = "獅子魚", createInterval = 4, createCount = 1, maxCount = 1, }, 
			{ roomName = "龜相迎賓", fishType = 13, fishName = "劍魚", createInterval = 5, createCount = 1, maxCount = 1, }, 
			{ roomName = "龜相迎賓", fishType = 14, fishName = "魔鬼魚", createInterval = 6, createCount = 1, maxCount = 1, }, 
			{ roomName = "龜相迎賓", fishType = 16, fishName = "蝙蝠魚", createInterval = 7, createCount = 1, maxCount = 1, }, 
			{ roomName = "龜相迎賓", fishType = 17, fishName = "錘頭魚", createInterval = 8, createCount = 1, maxCount = 1, }, 
			{ roomName = "龜相迎賓", fishType = 18, fishName = "大白鯊", createInterval = 9, createCount = 1, maxCount = 1, }, 
			{ roomName = "龜相迎賓", fishType = 19, fishName = "黃金大白鯊", createInterval = 10, createCount = 1, maxCount = 1, }, 
			{ roomName = "龜相迎賓", fishType = 20, fishName = "黃金魔鬼魚", createInterval = 15, createCount = 1, maxCount = 1, }, 
			{ roomName = "龜相迎賓", fishType = 22, fishName = "黃金水母", createInterval = 20, createCount = 1, maxCount = 1, }, 
			{ roomName = "龜相迎賓", fishType = 23, fishName = "黃金玳瑁", createInterval = 25, createCount = 1, maxCount = 1, }, 
			{ roomName = "龜相迎賓", fishType = 24, fishName = "黃金大章魚", createInterval = 30, createCount = 1, maxCount = 1, }, 
			{ roomName = "龜相迎賓", fishType = 25, fishName = "黃金鯨魚", createInterval = 35, createCount = 1, maxCount = 1, }, 
			{ roomName = "龜相迎賓", fishType = 28, fishName = "一網打盡", createInterval = 40, createCount = 1, maxCount = 1, }, 
			{ roomName = "龜相迎賓", fishType = 29, fishName = "大三元", createInterval = 35, createCount = 1, maxCount = 1, }, 
			{ roomName = "龜相迎賓", fishType = 32, fishName = "大四喜", createInterval = 30, createCount = 1, maxCount = 1, }, 
			{ roomName = "龜相迎賓", fishType = 37, fishName = "鑽頭魚", createInterval = 100, createCount = 1, maxCount = 1, }, 
			{ roomName = "龜相迎賓", fishType = 40, fishName = "藏寶蟹", createInterval = 130, createCount = 1, maxCount = 1, }, 
			{ roomName = "龜相迎賓", fishType = -1, fishName = "鱼组", createInterval = 1, createCount = 1, maxCount = 1, },  
		}
		
		
		
		return g
	end
}
