-- Generated by github.com/davyxu/tabtoy
-- Version: 3.1.3

return {
	init = function( g )
		
		g.MyData = { 
			{ itemid = 14001, name = "", enragedDuration = 0, }, 
			{ itemid = 14002, name = "", enragedDuration = 0, }, 
			{ itemid = 14003, name = "", enragedDuration = 2, }, 
			{ itemid = 14004, name = "", enragedDuration = 2, }, 
			{ itemid = 14005, name = "", enragedDuration = 2, },  
		}
		
		
		
		return g
	end
}
