-- Generated by github.com/davyxu/tabtoy
-- Version: 3.1.3

return {
	init = function( g )
		
		g.MyData = { 
			{ attachmentType = 11, attachmentName = "坦克", dropItems = {5032}, }, 
			{ attachmentType = 5, attachmentName = "话费", dropItems = {1003}, }, 
			{ attachmentType = 30, attachmentName = "金币", dropItems = {1001}, }, 
			{ attachmentType = 110, attachmentName = "闪电", dropItems = {}, },  
		}
		
		
		
		return g
	end
}
