-- Generated by github.com/davyxu/tabtoy
-- Version: 3.1.3

return {
	init = function( g )
		
		g.MyData = { 
			{ cannonLv = 10, nextCannonLv = 15, expMultiple = 1, requireItems = {5001}, requireItemsCount = {3}, rewardItems = {1001,4017}, rewardItemsCount = {800,1}, }, 
			{ cannonLv = 15, nextCannonLv = 20, expMultiple = 1, requireItems = {5001}, requireItemsCount = {4}, rewardItems = {1001,4020}, rewardItemsCount = {1000,1}, }, 
			{ cannonLv = 20, nextCannonLv = 25, expMultiple = 1, requireItems = {5001}, requireItemsCount = {5}, rewardItems = {1001}, rewardItemsCount = {1200}, }, 
			{ cannonLv = 25, nextCannonLv = 30, expMultiple = 1, requireItems = {5001}, requireItemsCount = {6}, rewardItems = {1001}, rewardItemsCount = {1500}, },  
		}
		
		
		
		return g
	end
}
