-- Generated by github.com/davyxu/tabtoy
-- Version: 3.1.3

return {
	init = function( g )
		
		g.MyData = { 
			{ fisheryName = "东方渔场", roomName = "龜相迎賓", roomID = 1, maxTalbeCount = 1000, enterLimitMultiple = {10,1000000}, enterLimitScore = {0,-1}, enterLimitLevel = {0,8}, enterLimitVIPLevel = {0,-1}, mapID = 3, open = true, fishTypes = {0,1,2,3,4,5,7,8,9,10,11,12,13,14,16,17,18,19,20,22,23,24,25,28,29,32,37,40}, }, 
			{ fisheryName = "东方渔场", roomName = "蟹將叛逃", roomID = 2, maxTalbeCount = 1000, enterLimitMultiple = {100,1000000}, enterLimitScore = {0,-1}, enterLimitLevel = {999,1000}, enterLimitVIPLevel = {0,-1}, mapID = 2, open = true, fishTypes = {0,1,2,3,4,5,7,8,9,10,11,12,13,14,16,17,18,19,20,22,25,26,35,36,41,42,43,44,37,38,127,128,129,130,150,153,154,155,169,174,175,176,177,178,179,189,192}, }, 
			{ fisheryName = "东方渔场", roomName = "幽靈來襲", roomID = 3, maxTalbeCount = 300, enterLimitMultiple = {500,1000000}, enterLimitScore = {0,-1}, enterLimitLevel = {999,1000}, enterLimitVIPLevel = {0,-1}, mapID = 5, open = true, fishTypes = {0,1,2,3,4,5,7,8,9,10,11,12,13,14,16,17,18,19,20,22,23,25,35,36,45,46,77,37,38,127,128,129,130,150,153,154,155,169,174,175,176,177,178,179,192}, }, 
			{ fisheryName = "东方渔场", roomName = "蟹將副本", roomID = 4, maxTalbeCount = 300, enterLimitMultiple = {400,1000000}, enterLimitScore = {300000,-1}, enterLimitLevel = {999,1000}, enterLimitVIPLevel = {0,-1}, mapID = 2, open = false, fishTypes = {0,1,2,3,4,5,7,8,9,10,11,12,13,14,16,17,18,19,20,22,23,24,25,35,36,78,37,38,127,128,129,130,150,153,154,155,169,174,175,176,177,178,179,192}, }, 
			{ fisheryName = "东方渔场", roomName = "人魚寶藏", roomID = 5, maxTalbeCount = 300, enterLimitMultiple = {800,1000000}, enterLimitScore = {300000,-1}, enterLimitLevel = {999,1000}, enterLimitVIPLevel = {0,-1}, mapID = 1, open = true, fishTypes = {0,1,2,3,4,5,7,8,9,10,11,12,13,14,16,17,18,19,20,22,23,25,35,36,37,38,40,127,128,129,130,150,153,154,155,169,174,175,176,177,178,179,192}, }, 
			{ fisheryName = "东方渔场", roomName = "幽靈副本", roomID = 6, maxTalbeCount = 300, enterLimitMultiple = {2500,1000000}, enterLimitScore = {1000000,-1}, enterLimitLevel = {999,1000}, enterLimitVIPLevel = {0,-1}, mapID = 5, open = true, fishTypes = {0,1,2,3,4,5,7,8,9,10,11,12,13,14,16,17,18,19,20,22,23,25,35,36,47,48,78,37,38,40,127,128,129,130,150,153,154,155,169,174,175,176,177,178,179,187,188,192}, }, 
			{ fisheryName = "东方渔场", roomName = "龍王降世", roomID = 7, maxTalbeCount = 100, enterLimitMultiple = {4000,1000000}, enterLimitScore = {2000000,-1}, enterLimitLevel = {999,1000}, enterLimitVIPLevel = {0,-1}, mapID = 4, open = true, fishTypes = {0,1,2,3,4,5,7,8,9,10,11,12,13,14,16,17,18,19,20,22,23,24,25,35,36,37,38,40,127,128,129,130,150,153,154,155,167,168,169,174,175,176,177,178,179,192}, }, 
			{ fisheryName = "西方渔场", roomName = "祥云瑞兽", roomID = 8, maxTalbeCount = 1000, enterLimitMultiple = {1000,1000000}, enterLimitScore = {1000000,-1}, enterLimitLevel = {999,1000}, enterLimitVIPLevel = {0,-1}, mapID = 9, open = true, fishTypes = {0,1,2,3,4,5,7,8,9,10,11,12,13,14,16,17,18,19,20,22,23,24,25,35,36,37,38,40,127,128,129,130,150,153,154,155,169,172,173,174,175,176,177,178,179,192}, }, 
			{ fisheryName = "西方渔场", roomName = "海魔獵場", roomID = 9, maxTalbeCount = 1000, enterLimitMultiple = {300,1000000}, enterLimitScore = {0,-1}, enterLimitLevel = {999,1000}, enterLimitVIPLevel = {0,-1}, mapID = 7, open = true, fishTypes = {35,36,80,81,82,83,85,86,37,38,127,128,129,130,131,132,133,134,135,137,138,139,140,141,142,143,144,145,146,147,148,150,153,154,155,169,174,175,176,177,178,179,192}, }, 
			{ fisheryName = "西方渔场", roomName = "高級獵魔場", roomID = 10, maxTalbeCount = 100, enterLimitMultiple = {1000,1000000}, enterLimitScore = {500000,-1}, enterLimitLevel = {999,1000}, enterLimitVIPLevel = {0,-1}, mapID = 8, open = false, fishTypes = {130,131,132,133,134,135,137,138,139,140,141,142,143,144,145,146,147,148,35,36,91,92,93,94,95,37,38,40,127,128,129,130,150,153,154,155,169,174,175,176,177,178,179,192}, }, 
			{ fisheryName = "西方渔场", roomName = "海底機械城", roomID = 11, maxTalbeCount = 1000, enterLimitMultiple = {5000,1000000}, enterLimitScore = {1000000,-1}, enterLimitLevel = {999,1000}, enterLimitVIPLevel = {0,-1}, mapID = 7, open = true, fishTypes = {19,20,22,23,25,107,108,111,112,113,114,115,116,117,118,119,120,121,122,127,128,129,130,150,153,154,155,169,170,171,174,175,176,177,178,179,192}, }, 
			{ fisheryName = "西方渔场", roomName = "超級至尊場", roomID = 12, maxTalbeCount = 1000, enterLimitMultiple = {10000,1000000}, enterLimitScore = {0,-1}, enterLimitLevel = {999,1000}, enterLimitVIPLevel = {4,-1}, mapID = 8, open = true, fishTypes = {0,1,2,3,4,5,7,8,9,10,11,12,13,14,16,17,18,19,20,22,23,24,25,35,36,73,37,38,39,40,123,124,125,126,127,128,129,130,150,169,174,175,176,177,178,179,192}, },  
		}
		
		
		
		return g
	end
}
