-- Generated by github.com/davyxu/tabtoy
-- Version: 3.1.3

return {
	init = function( g )
		
		g.MyData = { 
			{ fisheryName = "东方渔场", roomName = "龜相迎賓", roomID = 1, maxTalbeCount = 1000, enterLimitMultiple = {10,1000000}, enterLimitScore = {0,-1}, enterLimitLevel = {0,8}, enterLimitVIPLevel = {0,-1}, mapID = 3, open = true, fishTypes = {37,24,23,25,19,20,28,29,32,18,17,16,14,12,10,9,8,7,5,3,1,0,40,22,13,11,4,2}, }, 
			{ fisheryName = "东方渔场", roomName = "蟹將叛逃", roomID = 2, maxTalbeCount = 1000, enterLimitMultiple = {100,1000000}, enterLimitScore = {0,-1}, enterLimitLevel = {999,1000}, enterLimitVIPLevel = {0,-1}, mapID = 2, open = true, fishTypes = {37,24,23,25,19,20,28,29,32,18,17,16,14,12,10,9,8,7,5,3,1,0,40,22,13,11,4,2}, }, 
			{ fisheryName = "东方渔场", roomName = "幽靈來襲", roomID = 3, maxTalbeCount = 300, enterLimitMultiple = {500,1000000}, enterLimitScore = {0,-1}, enterLimitLevel = {999,1000}, enterLimitVIPLevel = {0,-1}, mapID = 5, open = true, fishTypes = {37,24,23,25,19,20,28,29,32,18,17,16,14,12,10,9,8,7,5,3,1,0,40,22,13,11,4,2}, }, 
			{ fisheryName = "东方渔场", roomName = "人魚寶藏", roomID = 4, maxTalbeCount = 300, enterLimitMultiple = {800,1000000}, enterLimitScore = {300000,-1}, enterLimitLevel = {999,1000}, enterLimitVIPLevel = {0,-1}, mapID = 1, open = true, fishTypes = {37,24,23,25,19,20,28,29,32,18,17,16,14,12,10,9,8,7,5,3,1,0,40,22,13,11,4,2}, }, 
			{ fisheryName = "东方渔场", roomName = "幽靈副本", roomID = 5, maxTalbeCount = 300, enterLimitMultiple = {2500,1000000}, enterLimitScore = {1000000,-1}, enterLimitLevel = {999,1000}, enterLimitVIPLevel = {0,-1}, mapID = 5, open = true, fishTypes = {37,24,23,25,19,20,28,29,32,18,17,16,14,12,10,9,8,7,5,3,1,0,40,22,13,11,4,2}, }, 
			{ fisheryName = "东方渔场", roomName = "龍王降世", roomID = 6, maxTalbeCount = 100, enterLimitMultiple = {4000,1000000}, enterLimitScore = {2000000,-1}, enterLimitLevel = {999,1000}, enterLimitVIPLevel = {0,-1}, mapID = 4, open = true, fishTypes = {37,24,23,25,19,20,28,29,32,18,17,16,14,12,10,9,8,7,5,3,1,0,40,22,13,11,4,2}, }, 
			{ fisheryName = "西方渔场", roomName = "祥云瑞兽", roomID = 7, maxTalbeCount = 1000, enterLimitMultiple = {1000,1000000}, enterLimitScore = {1000000,-1}, enterLimitLevel = {999,1000}, enterLimitVIPLevel = {0,-1}, mapID = 9, open = true, fishTypes = {19,20,29,18,17,16,14,9,7,3,1,0,22,13,11}, }, 
			{ fisheryName = "西方渔场", roomName = "海魔獵場", roomID = 8, maxTalbeCount = 1000, enterLimitMultiple = {300,1000000}, enterLimitScore = {0,-1}, enterLimitLevel = {999,1000}, enterLimitVIPLevel = {0,-1}, mapID = 7, open = true, fishTypes = {146,145,144,143,142,140,139,138,137,135,134,133,132,131,40,148,147}, }, 
			{ fisheryName = "西方渔场", roomName = "海底機械城", roomID = 9, maxTalbeCount = 1000, enterLimitMultiple = {5000,1000000}, enterLimitScore = {1000000,-1}, enterLimitLevel = {999,1000}, enterLimitVIPLevel = {0,-1}, mapID = 7, open = true, fishTypes = {170,114,171,122,121,116,117,113,112,118,115,111,120,119}, }, 
			{ fisheryName = "西方渔场", roomName = "超級至尊場", roomID = 10, maxTalbeCount = 1000, enterLimitMultiple = {10000,1000000}, enterLimitScore = {0,-1}, enterLimitLevel = {999,1000}, enterLimitVIPLevel = {4,-1}, mapID = 8, open = true, fishTypes = {19,20,29,18,17,16,14,9,7,3,1,0,123,124,125,13,11,4,2}, },  
		}
		
		
		
		return g
	end
}
