-- Generated by github.com/davyxu/tabtoy
-- Version: 3.1.3

return {
	init = function( g )
		
		g.MyData = { 
			{ skillid = 1, name = "冰冻", duration = 10, autoStop = true, catchRadio = 1, openVipLv = 0, freeFisheryIDs = {}, consumeItemIDs = {1002,3002}, consumeItemIDsCount = {5,1}, }, 
			{ skillid = 2, name = "瞄准", duration = 20, autoStop = true, catchRadio = 1, openVipLv = 0, freeFisheryIDs = {}, consumeItemIDs = {1002,3001}, consumeItemIDsCount = {2,1}, }, 
			{ skillid = 3, name = "狂暴", duration = 20, autoStop = true, catchRadio = 2, openVipLv = 2, freeFisheryIDs = {}, consumeItemIDs = {1002,3001}, consumeItemIDsCount = {10,1}, }, 
			{ skillid = 4, name = "自动发炮", duration = -1, autoStop = false, catchRadio = 1, openVipLv = 0, freeFisheryIDs = {}, consumeItemIDs = {}, consumeItemIDsCount = {}, },  
		}
		
		
		
		return g
	end
}
