-- Generated by github.com/davyxu/tabtoy
-- Version: 3.1.3

return {
	init = function( g )
		
		g.MyData = { 
			{ itemid = 6001, itemCount = 1, itemName = "新手炮", subItemIds = {12001,12002}, subItemIdsCount = {1,2}, rate = 100, }, 
			{ itemid = 6002, itemCount = 1, itemName = "航海先锋", subItemIds = {12001,12002}, subItemIdsCount = {1,2}, rate = 100, }, 
			{ itemid = 6003, itemCount = 1, itemName = "梦幻蝶影", subItemIds = {12002,12003}, subItemIdsCount = {3,4}, rate = 100, }, 
			{ itemid = 6004, itemCount = 1, itemName = "自由星河", subItemIds = {12002,12003}, subItemIdsCount = {1,2}, rate = 100, }, 
			{ itemid = 6005, itemCount = 1, itemName = "帝王之姿", subItemIds = {12002,12003}, subItemIdsCount = {1,2}, rate = 100, }, 
			{ itemid = 6006, itemCount = 1, itemName = "红粉佳人", subItemIds = {12002,12004}, subItemIdsCount = {1,2}, rate = 100, }, 
			{ itemid = 7001, itemCount = 1, itemName = "新手炮座", subItemIds = {12001,12002}, subItemIdsCount = {1,2}, rate = 100, }, 
			{ itemid = 7002, itemCount = 1, itemName = "深海堡垒", subItemIds = {12002,12003}, subItemIdsCount = {3,4}, rate = 100, }, 
			{ itemid = 7003, itemCount = 1, itemName = "雷霆王座", subItemIds = {12001,12002}, subItemIdsCount = {1,2}, rate = 100, }, 
			{ itemid = 7004, itemCount = 1, itemName = "水神宝座", subItemIds = {12002,12003}, subItemIdsCount = {3,4}, rate = 100, }, 
			{ itemid = 7005, itemCount = 1, itemName = "灼日王座", subItemIds = {12001,12002}, subItemIdsCount = {1,2}, rate = 100, }, 
			{ itemid = 7006, itemCount = 1, itemName = "莲花宝座", subItemIds = {12002,12003}, subItemIdsCount = {3,4}, rate = 100, }, 
			{ itemid = 8001, itemCount = 1, itemName = "天穹之翼(1天)", subItemIds = {12001,12002}, subItemIdsCount = {1,2}, rate = 100, }, 
			{ itemid = 8002, itemCount = 1, itemName = "冰蓝之翼(1天)", subItemIds = {12002,12003}, subItemIdsCount = {3,4}, rate = 100, },  
		}
		
		
		
		return g
	end
}
