-- Generated by github.com/davyxu/tabtoy
-- Version: 3.1.3

return {
	init = function( g )
		
		g.MyData = { 
			{ itemid = 11001, name = "", enragedDuration = 0, }, 
			{ itemid = 11002, name = "", enragedDuration = 0, }, 
			{ itemid = 11003, name = "", enragedDuration = 2, }, 
			{ itemid = 11004, name = "", enragedDuration = 2, }, 
			{ itemid = 11005, name = "", enragedDuration = 2, },  
		}
		
		
		
		return g
	end
}
